# Generated by Django 3.2.18 on 2023-08-09 16:25

from django.db import migrations
import nautobot.core.models.fields


class Migration(migrations.Migration):
    dependencies = [
        ("extras", "0094_remove_slugs"),
        ("nautobot_data_validation_engine", "0004_created_datetime"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="minmaxvalidationrule",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="regularexpressionvalidationrule",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="requiredvalidationrule",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="uniquevalidationrule",
            name="slug",
        ),
        migrations.AlterField(
            model_name="datacompliance",
            name="tags",
            field=nautobot.core.models.fields.TagsField(through="extras.TaggedItem", to="extras.Tag"),
        ),
        migrations.AlterField(
            model_name="minmaxvalidationrule",
            name="tags",
            field=nautobot.core.models.fields.TagsField(through="extras.TaggedItem", to="extras.Tag"),
        ),
        migrations.AlterField(
            model_name="regularexpressionvalidationrule",
            name="tags",
            field=nautobot.core.models.fields.TagsField(through="extras.TaggedItem", to="extras.Tag"),
        ),
        migrations.AlterField(
            model_name="requiredvalidationrule",
            name="tags",
            field=nautobot.core.models.fields.TagsField(through="extras.TaggedItem", to="extras.Tag"),
        ),
        migrations.AlterField(
            model_name="uniquevalidationrule",
            name="tags",
            field=nautobot.core.models.fields.TagsField(through="extras.TaggedItem", to="extras.Tag"),
        ),
    ]
