# Generated by Django 4.2.16 on 2024-10-17 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nautobot_data_validation_engine', '0006_add_field_defaults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datacompliance',
            name='compliance_class_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='datacompliance',
            name='validated_attribute',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
